### PR TITLE
Update data to 2019-06-15

### PR DESCRIPTION
**Pull request by kroeckx**

### CODE REVIEW

**Comment by kroeckx** [comment]
Can you merge this?

**Comment by gplv2** [comment]
Sorry , didn't notice this, the diff is too large to view here, are these code fixes or just a data update ?  Data updates I do on the server because I want to see the results, from time to time there is a data issue which needs attention.

**Comment by kroeckx** [comment]
This is only a data en metadata update. You didn't update some of
the meta data files the last time.

**Comment by gplv2** [comment]
Hi, since I did a more recent update I'm going to close this as it would put the data back.   Best to contact me in https://riot.im/app/#/room/#osmbe-dev:matrix.org next time so I'm aware, I don't get live notifications from github, it would be too much to handle.  Tx for the effort though.

**Pull request closed without merging**
